export const HttpStatusCode = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export type HttpStatusCode = (typeof HttpStatusCode)[keyof typeof HttpStatusCode];

export const ErrorCode = {
  SUCCESS: 200,
  PARAMS_ERROR: 400,
  NOT_LOGIN_ERROR: 401,
  NO_AUTH_ERROR: 403,
  NOT_FOUND_ERROR: 404,
  SYSTEM_ERROR: 500,
  OPERATION_ERROR: 501,
  DB_CONNECTION_ERROR: 510,
  DB_CONNECTION_TIMEOUT: 511,
  DB_CONNECTION_NOT_FOUND: 512,
  DB_CONNECTION_ALREADY_EXISTS: 513,
  DB_CONNECTION_CONFIG_ERROR: 514,
  DRIVER_NOT_FOUND: 520,
  DRIVER_LOAD_ERROR: 521,
  DRIVER_DOWNLOAD_ERROR: 522,
  DRIVER_VERSION_NOT_SUPPORTED: 523,
  DRIVER_FILE_CORRUPTED: 524,
  SQL_SYNTAX_ERROR: 530,
  SQL_EXECUTION_ERROR: 531,
  SQL_TIMEOUT_ERROR: 532,
  TRANSACTION_COMMIT_ERROR: 533,
  TRANSACTION_ROLLBACK_ERROR: 534,
  PLUGIN_NOT_FOUND: 540,
  PLUGIN_LOAD_ERROR: 541,
  PLUGIN_NOT_SUPPORT: 542,
  PLUGIN_INIT_ERROR: 543,
  FILE_NOT_FOUND: 550,
  FILE_READ_ERROR: 551,
  FILE_WRITE_ERROR: 552,
  FILE_DELETE_ERROR: 553,
  FILE_FORMAT_NOT_SUPPORTED: 554,
  FILE_SIZE_EXCEEDED: 555,
  VALIDATION_ERROR: 560,
  REQUIRED_FIELD_EMPTY: 561,
  FIELD_FORMAT_ERROR: 562,
  FIELD_LENGTH_EXCEEDED: 563,
  FIELD_VALUE_OUT_OF_RANGE: 564,
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const isAuthError = (code: number): boolean => {
  return code === ErrorCode.NOT_LOGIN_ERROR;
};

export const isForbiddenError = (code: number): boolean => {
  return code === ErrorCode.NO_AUTH_ERROR;
};
